import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12

[font.bold]
family = "CaskaydiaCove Nerd Font Propo"
style = "Bold"
[font.bold_italic]
family = "CaskaydiaCove Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Propo"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Propo"
style = "Regular"


